services:
  postgres:
    image: postgres:latest
    container_name: postgres_wave
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wave-network

  redis:
    image: redis:latest
    container_name: redis_wave
    ports:
      - "6379:6379"
    networks:
      - wave-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_wave
    environment:
      - DB_SOURCE=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable
      - REDIS_ADDR=redis:6379
      - ENV=development
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - wave-network

networks:
  wave-network:
    driver: bridge

volumes:
  postgres_data:
