// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetUserByID(ctx context.Context, id string) (User, error)
}

var _ Querier = (*Queries)(nil)
