// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateCheckoutSession(ctx context.Context, arg CreateCheckoutSessionParams) error
	// Secrets CRUD
	CreateSecret(ctx context.Context, arg CreateSecretParams) error
	// Sessions CRUD
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	// Users CRUD
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteExpiredSessions(ctx context.Context, expiresAt string) error
	DeleteSecret(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	GetCheckoutSession(ctx context.Context, id string) (CheckoutSession, error)
	GetCheckoutSessionByTransactionID(ctx context.Context, transactionID sql.NullString) (CheckoutSession, error)
	GetCheckoutSessionsByClientReference(ctx context.Context, clientReference sql.NullString) ([]CheckoutSession, error)
	GetSecretByHash(ctx context.Context, secretHash string) (Secret, error)
	GetSecretByID(ctx context.Context, id string) (Secret, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByPhone(ctx context.Context, phoneNumber string) (User, error)
	ListCheckoutSessionsByUser(ctx context.Context, arg ListCheckoutSessionsByUserParams) ([]CheckoutSession, error)
	ListSecretsByUser(ctx context.Context, arg ListSecretsByUserParams) ([]Secret, error)
	ListSessionsByUser(ctx context.Context, arg ListSessionsByUserParams) ([]Session, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListWebhooksByUser(ctx context.Context, arg ListWebhooksByUserParams) ([]Secret, error)
	RevokeSecret(ctx context.Context, arg RevokeSecretParams) error
	UpdateCheckoutSessionRefund(ctx context.Context, arg UpdateCheckoutSessionRefundParams) error
	UpdateCheckoutSessionStatus(ctx context.Context, arg UpdateCheckoutSessionStatusParams) error
	UpdateUserPinHash(ctx context.Context, arg UpdateUserPinHashParams) error
}

var _ Querier = (*Queries)(nil)
