// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type CheckoutSession struct {
	ID                      string
	Amount                  string
	CheckoutStatus          string
	ClientReference         sql.NullString
	Currency                string
	ErrorUrl                string
	SuccessUrl              string
	BusinessName            sql.NullString
	PaymentStatus           string
	TransactionID           sql.NullString
	AggregatedMerchantID    sql.NullString
	RestrictPayerMobile     sql.NullString
	EnforcePayerMobile      sql.NullString
	WaveLaunchUrl           string
	WhenCreated             string
	WhenExpires             string
	WhenCompleted           sql.NullString
	WhenRefunded            sql.NullString
	LastPaymentErrorCode    sql.NullString
	LastPaymentErrorMessage sql.NullString
}

type Secret struct {
	ID          string
	UserID      string
	SecretHash  string
	SecretType  string
	Permissions string
	DisplayHint string
	CreatedAt   string
	RevokedAt   sql.NullString
}

type Session struct {
	ID        string
	UserID    string
	ExpiresAt string
	CreatedAt string
}

type User struct {
	ID          string
	PhoneNumber string
	PinHash     string
	CreatedAt   string
}
