// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateCheckoutSession(ctx context.Context, arg CreateCheckoutSessionParams) error
	GetCheckoutSession(ctx context.Context, id string) (CheckoutSession, error)
}

var _ Querier = (*Queries)(nil)
